server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.41:3306/yeb?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
    username: root
    password: Li@3188057.
    #连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小连接数
      minimum-idle: 5
      #空闲连接最大存活时间 默认 10分钟
      idle-timeout: 180000
      #最大连接数 10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间 0表示永久存活 默认30分钟
      max-lifetime: 180000
      #连接超时时间 默认30秒
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
    #连接名


# redis相关配置
  redis:
    host: 192.168.188.41
    #超时时间
    timeout: 10000ms
    port: 6379
    database: 0
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 1024
        #最大连接阻塞等待时间 默认 -1
        max-wait: 10000ms
        #最大空闲连接
        min-idle: 5


  #rabbitmq设置
  rabbitmq:
    #用户名
    username: admin
    #密码
    password: 123
    #rabbitmq服务器地址
    host: 192.168.188.41
    #端口
    port: 5672



mybatis-plus:
  #mapper-映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  #配置mybatis数据库的返回类型别名
  type-aliases-package: com.xxxx.server.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false
logging:
  level:
    com.xxxx.server.mapper: debug






